services:
  flight_delay:
    image: python:3.10  # Use the official Python image from Docker Hub
    volumes:
      - .:/usr/src/app  # Mount the local 'data' folder into the container
      - ../.kaggle:/root/.kaggle  # Mount your local .kaggle folder into the container
    working_dir: /usr/src/app  # Set the working directory inside the container
    command: ["python", "scripts/ingestion/ingest.py"]  # Automatically run the ingestion script
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs are shown in real-time (useful for debugging)
      - REINGEST_DATA=false
    # ports:
    #   - "8888:8888"  # Optional: Expose a port if you want to use a Jupyter Notebook or similar

    entrypoint: >
      bash -c "
        chmod 600 /root/.kaggle/kaggle.json &&  # Ensure the API is not readable by others on the system
        source /usr/src/app/env/Scripts/activate &&  # Activate the virtual environment
        pip install -r /usr/src/app/requirements.txt &&   # Install requirements
        python scripts/ingestion/ingest.py  # Run the ingestion script
      "
